drop table if exists AirlineDataset;

create table AirlineDataset (
id					integer identity primary key,
Year               	integer,
Month             	integer,
DayofMonth        	integer,
DayOfWeek         	integer,
DepTime           	integer,
CRSDepTime        	integer,
ArrTime           	integer,
CRSArrTime        	integer,
UniqueCarrier     	varchar(256),
FlightNum         	integer,
TailNum           	varchar(256),
ActualElapsedTime 	integer,
CRSElapsedTime    	integer,
AirTime           	varchar(256),
ArrDelay          	integer,
DepDelay          	integer,
Origin            	varchar(256),
Dest              	varchar(256),
Distance          	integer,
TaxiIn            	varchar(256),
TaxiOut           	varchar(256),
Cancelled         	integer,
CancellationCode  	varchar(256),
Diverted          	integer,
CarrierDelay      	varchar(256),
WeatherDelay      	varchar(256),
NASDelay          	varchar(256),
SecurityDelay     	varchar(256),
LateAircraftDelay 	varchar(256),
--Iata                varchar(256),
Airport             varchar(256),
City                varchar(256),
State               varchar(256),
Country             varchar(256),
Lat                 double,
Long                double,
--Code                varchar(256),
Description         varchar(256));